### ISSUE TITLE
GitHub Universe Cloud Skills Challenge, prueba de conclusion

### ISSUE THREAD

**Issue by AndreaGriffiths11** [githubpresente/msft-reto#1]
Al finalizar el evento, carga una captura de pantalla de la página de conclusiones y súbela a este "issue" como un comentario para participar en el sorteo de un crédito de examen.

**Comment by jdrestre** [comment]
![Github Universe Cloud Skills Challenge](https://github.com/githubpresente/msft-reto/assets/53844590/868d6544-bb2b-431e-8392-ec57eeab2ad9)

Aprendiendo de Azure AI Vision y Azure OpenAI Cognitive Service, todos las opciones y utilidades que se pueden generar en la nube. Muy bien explicadas los módulos paso a paso y al final un reto muy acorde con lo aprendido el desafío. Muchas gracias

**Comment by AndreaGriffiths11** [comment]
Felicidades Juan David!

**Comment by AndreaGriffiths11** [comment]
Hola @jdrestre Juan David, por favor me escribes a andreagriffiths11@github.com para gestionar el credito para el examen! Gracias

**Comment by luiscarlosmedina** [comment]
![image](https://github.com/githubpresente/msft-reto/assets/75760949/946685e7-ea22-4103-9139-bc83c162603f)
Hola, complete el reto!

**Comment by jorgeluismorales** [comment]
![Screenshot_2023-12-15-02-11-40](https://github.com/githubpresente/msft-reto/assets/53586348/a5f757d8-eca5-4a76-aeb5-186dba523c1e)
