### ISSUE TITLE
Participación

### ISSUE THREAD

**Issue by BrunoGGM** [githubpresente/msft-reto#2]
¡Hola!, por casualidad encontré este repo en mi home de GitHub, quisiera saber si cualquier persona puede participar en el sorteo.

**Comment by luiscarlosmedina** [comment]
![image](https://github.com/githubpresente/msft-reto/assets/75760949/8e7957b7-edb7-4ad7-97c2-38714c5b441c)
Hola, mi evidencia completando el reto!!
